spring.main.banner-mode=off
server.port=8096

spring.datasource.url=jdbc:postgresql://localhost:5432/centrifugo
spring.datasource.username=centrifugo
spring.datasource.password=centrifugo

centrifugo.hmac-secret=bc33457f-c7f3-4ecf-840a-21f3b8274476

cors.allowed-origins=http://localhost:4179,http://localhost:5173
cors.allowed-methods=GET,POST
cors.allowed-headers=*
cors.allow-credentials=true
cors.max-age=3600
